root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server.exe ./cmd/server"
  bin = "./tmp/server.exe"
  include_ext = ["go", "html"]
  exclude_dir = ["tmp", "bin", "web"]
  delay = 500

[misc]
  clean_on_exit = true
