apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: altcha
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: altcha.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: altcha
            port:
              name: http
  tls:
  - hosts:
    - altcha.example.com
    secretName: altcha-tls
