apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yaml
- svc.yaml
- ing.yaml
- pdb.yaml
secretGenerator:
- name: altcha-secret
  envs:
  - .env
images:
- name: docker.io/rayshoo/altcha
  newTag: latest